    name: Deploy Frontend
    on:
      push:
        branches:
          - main # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: docker-react
              environment_name: docker-react-env
              existing_bucket_name: elasticbeanstalk-us-east-1-980256607140
              region: us-east-1
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip